{
 "title": "GRPC 运行监控",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "native_region",
    "label": "地区",
    "query": {
     "query": "label_values(runtime_cpu_load_1,native_region)"
    }
   },
   {
    "name": "native_env",
    "label": "环境",
    "query": {
     "query": "label_values(runtime_cpu_load_1{native_region=~\"$native_region\"},native_env)"
    }
   },
   {
    "name": "app",
    "label": "应用名",
    "query": {
     "query": "label_values(runtime_cpu_load_1{native_env=~\"$native_env\", native_region=~\"$native_region\"},app)"
    }
   },
   {
    "name": "pod_name",
    "label": "实例名",
    "query": {
     "query": "label_values(runtime_cpu_load_1{native_region=~\"$native_region\", native_env=~\"$native_env\", app=~\"$app\"},pod_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "GRPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "grpc_client_request",
     "type": "timeseries",
     "description": "GRPC 请求数量(当前服务请求其他服务)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(grpc_client_request{from_region=\"$native_region\", from_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[1m])",
       "legendFormat": "{{pod_name}}-{{to_method}}"
      }
     ]
    },
    {
     "title": "grpc_server_request",
     "type": "timeseries",
     "description": "GRPC 每秒请求数量(其他服务请求当前服务)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(grpc_server_request{to_region=\"$native_region\", to_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[1m])",
       "legendFormat": "{{pod_name}}-{{to_method}}"
      }
     ]
    },
    {
     "title": "grpc_client_request 成功率",
     "type": "timeseries",
     "description": "GRPC 请求数量(当前服务请求其他服务)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(sum by (to_method) ( rate(grpc_client_request{from_region=\"$native_region\", from_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\", is_error=\"0\"}[1m]) )) / (sum by (to_method) (rate(grpc_client_request{from_region=\"$native_region\", from_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[1m])))",
       "legendFormat": "{{to_method}}"
      }
     ]
    },
    {
     "title": "grpc_server_request 成功率",
     "type": "timeseries",
     "description": "GRPC 请求成功率(其他服务请求当前服务)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(sum by (to_method) (rate(grpc_server_request{to_region=\"$native_region\", to_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\", is_error=\"0\"}[1m]))) / (sum by (to_method) (rate(grpc_server_request{to_region=\"$native_region\", to_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[1m])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "grpc_client_latency",
     "type": "timeseries",
     "description": "GRPC 客户端延迟(当前服务请求其他服务)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "irate(grpc_client_latency_sum{from_region=\"$native_region\", from_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[1m]) / rate(grpc_client_latency_count{from_region=\"$native_region\", from_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[1m])",
       "legendFormat": "{{pod_name}}-{{to_method}}"
      }
     ]
    },
    {
     "title": "grpc_server_latency",
     "type": "timeseries",
     "description": "GRPC 服务端延时(其他服务请求当前服务)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(grpc_server_latency_sum{to_region=\"$native_region\", to_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[1m]) / rate(grpc_server_latency_count{to_region=\"$native_region\", to_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[1m])",
       "legendFormat": "{{pod_name}}-{{to_method}}"
      }
     ]
    }
   ]
  }
 ]
}