{
 "title": "HTTP 运行监控",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "native_region",
    "label": "地区",
    "query": {
     "query": "label_values(runtime_cpu_load_1,native_region)"
    }
   },
   {
    "name": "native_env",
    "label": "环境",
    "query": {
     "query": "label_values(runtime_cpu_load_1{native_region=~\"$native_region\"},native_env)"
    }
   },
   {
    "name": "app",
    "label": "应用名",
    "query": {
     "query": "label_values(http_request{to_env=~\"$native_env\", to_region=~\"$native_region\"},app)"
    }
   },
   {
    "name": "pod_name",
    "label": "实例名",
    "query": {
     "query": "label_values(runtime_cpu_load_1{native_region=~\"$native_region\", native_env=~\"$native_env\", app=~\"$app\"},pod_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "整体视角",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "http_request",
     "type": "timeseries",
     "description": "HTTP 请求数量",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum (rate(http_request{to_region=\"$native_region\", to_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[1m]))",
       "legendFormat": "QPS"
      }
     ]
    },
    {
     "title": "http_latency",
     "type": "timeseries",
     "description": "请求响应时间",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(http_latency_sum{to_region=\"$native_region\", to_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[1m])) / sum(rate(http_latency_count{to_region=\"$native_region\", to_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[1m]))",
       "legendFormat": "平均延时"
      }
     ]
    },
    {
     "title": "HTTP 请求失败率",
     "type": "timeseries",
     "description": "HTTP 请求失败率",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(sum (rate(http_request{to_region=\"$native_region\", to_env=~\"$native_env\", app=~\"$app\",is_error=\"1\",pod_name=~\"$pod_name\"}[1m]))) / (sum (rate(http_request{to_region=\"$native_region\", to_env=~\"$native_env\", app=~\"$app\",pod_name=~\"$pod_name\"}[1m])))",
       "legendFormat": "Error Rate"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP 接口视角",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "http_request",
     "type": "timeseries",
     "description": "HTTP 请求数量",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 128 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (uri) (rate(http_request{to_region=\"$native_region\", to_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "http_latency",
     "type": "timeseries",
     "description": "请求响应时间",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 135 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum by(uri) (rate(http_latency_sum{to_region=\"$native_region\", to_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[1m])) / sum by(uri) (rate(http_latency_count{to_region=\"$native_region\", to_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HTTP 请求失败率",
     "type": "timeseries",
     "description": "HTTP 请求失败率",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(sum by (uri) (rate(http_request{to_region=\"$native_region\", to_env=~\"$native_env\", app=~\"$app\",is_error=\"1\",pod_name=~\"$pod_name\"}[1m]))) / (sum by (uri) (rate(http_request{to_region=\"$native_region\", to_env=~\"$native_env\", app=~\"$app\",pod_name=~\"$pod_name\"}[1m])))",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "HTTP 请求失败错误情况(接口视角)",
     "type": "timeseries",
     "description": "HTTP 请求失败错误情况",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 147 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (uri) (rate(http_request{to_region=\"$native_region\", to_env=~\"$native_env\", app=~\"$app\",is_error=\"1\", pod_name=~\"$pod_name\"}[1m]))",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "HTTP 请求失败错误情况(错误码视角)",
     "type": "timeseries",
     "description": "HTTP 请求失败错误情况",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 153 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (err_code) (rate(http_request{to_region=\"$native_region\", to_env=~\"$native_env\", app=~\"$app\",is_error=\"1\", pod_name=~\"$pod_name\"}[1m]))",
       "legendFormat": "{{err_code}}"
      }
     ]
    },
    {
     "title": "HTTP 请求失败错误情况(接口+错误码视角)",
     "type": "timeseries",
     "description": "HTTP 请求失败错误情况",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 161 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (uri, err_code) (rate(http_request{to_region=\"$native_region\", to_env=~\"$native_env\", app=~\"$app\",is_error=\"1\", pod_name=~\"$pod_name\"}[1m]))",
       "legendFormat": "{{uri}}-{{err_code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod 视角",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "http_request",
     "type": "timeseries",
     "description": "HTTP 请求数量",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (pod_name) (rate(http_request{to_region=\"$native_region\", to_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "http_latency",
     "type": "timeseries",
     "description": "请求响应时间",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum by(pod_name) (rate(http_latency_sum{to_region=\"$native_region\", to_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[1m])) / sum by(pod_name) (rate(http_latency_count{to_region=\"$native_region\", to_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HTTP 请求失败率",
     "type": "timeseries",
     "description": "HTTP 请求失败率",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(sum by (pod_name) (rate(http_request{to_region=\"$native_region\", to_env=~\"$native_env\", app=~\"$app\",is_error=\"1\",pod_name=~\"$pod_name\"}[1m]))) / (sum by (pod_name) (rate(http_request{to_region=\"$native_region\", to_env=~\"$native_env\", app=~\"$app\",pod_name=~\"$pod_name\"}[1m])))",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "HTTP 请求失败错误情况(Pod 视角)",
     "type": "timeseries",
     "description": "HTTP 请求失败错误情况",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (pod_name) (rate(http_request{to_region=\"$native_region\", to_env=~\"$native_env\", app=~\"$app\",is_error=\"1\", pod_name=~\"$pod_name\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HTTP 请求失败错误情况(Pod + 错误码视角)",
     "type": "timeseries",
     "description": "HTTP 请求失败错误情况",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (pod_name, err_code) (rate(http_request{to_region=\"$native_region\", to_env=~\"$native_env\", app=~\"$app\",is_error=\"1\", pod_name=~\"$pod_name\"}[1m]))",
       "legendFormat": "{{pod_name}}-{{err_code}}"
      }
     ]
    }
   ]
  }
 ]
}