{
 "title": "服务运行监控",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "native_env",
    "label": "环境",
    "query": {
     "query": "label_values(runtime_cpu_load_1,native_env)"
    }
   },
   {
    "name": "app",
    "label": "应用名",
    "query": {
     "query": "label_values(runtime_cpu_load_1{native_env=\"$native_env\"},app)"
    }
   },
   {
    "name": "pod_name",
    "label": "实例名",
    "query": {
     "query": "label_values(runtime_cpu_load_1{app=\"$app\"},pod_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "MySQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "mysql_max_open_connections",
   "type": "timeseries",
   "description": "数据库最大开放连接数",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "mysql_max_open_connections{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}",
     "legendFormat": "{{pod_name}} - {{name}}"
    }
   ]
  },
  {
   "title": "mysql_open_connections",
   "type": "timeseries",
   "description": "当前建立的连接总数（使用中 + 空闲）",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "mysql_open_connections{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}",
     "legendFormat": "{{pod_name}} - {{name}}"
    }
   ]
  },
  {
   "title": "mysql_idle",
   "type": "timeseries",
   "description": "当前空闲连接数",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "mysql_idle{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}",
     "legendFormat": "{{pod_name}} - {{name}}"
    }
   ]
  },
  {
   "title": "mysql_in_use",
   "type": "timeseries",
   "description": "当前正在使用的连接数",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "mysql_in_use{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}",
     "legendFormat": "{{pod_name}} - {{name}}"
    }
   ]
  },
  {
   "title": "mysql_wait_count(最好和 mysql_wait_duration 配合用)",
   "type": "timeseries",
   "description": "每秒等待连接的总次数",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": " rate(mysql_wait_count{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[5m])",
     "legendFormat": "{{pod_name}} - {{name}}"
    }
   ]
  },
  {
   "title": "mysql_wait_duration(错误)",
   "type": "timeseries",
   "description": "等待连接的总时间",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "rate(mysql_wait_duration_sum{native_env=~\"$native_env\", app=~\"$app\"}[5m]) / rate(mysql_wait_duration_count{native_env=~\"$native_env\", app=~\"$app\"}[5m])",
     "legendFormat": "{{pod_name}} - {{name}}"
    }
   ]
  },
  {
   "title": "mysql_max_idle_closed",
   "type": "timeseries",
   "description": "因空闲连接数超限而关闭的连接",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "mysql_max_idle_closed{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}",
     "legendFormat": "{{pod_name}} - {{name}}"
    }
   ]
  },
  {
   "title": "mysql_max_idle_time_closed",
   "type": "timeseries",
   "description": "因空闲时间超限而关闭的连接",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "mysql_max_idle_time_closed{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}",
     "legendFormat": "{{pod_name}} - {{name}}"
    }
   ]
  },
  {
   "title": "mysql_max_lifetime_closed",
   "type": "timeseries",
   "description": "因生命周期超限而关闭的连接",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "mysql_max_lifetime_closed{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}",
     "legendFormat": "{{pod_name}} - {{name}}"
    }
   ]
  }
 ]
}