{
 "title": "Redis 运行监控",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "native_region",
    "label": "地区",
    "query": {
     "query": "label_values(runtime_cpu_load_1,native_region)"
    }
   },
   {
    "name": "native_env",
    "label": "环境",
    "query": {
     "query": "label_values(runtime_cpu_load_1{native_region=~\"$native_region\"},native_env)"
    }
   },
   {
    "name": "app",
    "label": "应用名",
    "query": {
     "query": "label_values(runtime_cpu_load_1{native_env=~\"$native_env\", native_region=~\"$native_region\"},app)"
    }
   },
   {
    "name": "pod_name",
    "label": "实例名",
    "query": {
     "query": "label_values(runtime_cpu_load_1{native_region=~\"$native_region\", native_env=~\"$native_env\", app=~\"$app\"},pod_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "整体视角",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "redis_hits",
     "type": "timeseries",
     "description": "每秒从池中成功获取空闲连接的次数",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "avg by(name) (rate(redis_hits{native_region=\"$native_region\", native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[1m]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "redis_misses",
     "type": "timeseries",
     "description": "每秒未能从池中获取连接，需要新建连接的次数",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "avg by (name) (rate(redis_misses{native_region=\"$native_region\", native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[1m]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "redis_total_conns",
     "type": "timeseries",
     "description": "池中总连接数（活跃 + 空闲）",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 77 },
     "targets": [
      {
       "expr": "avg by(name) (redis_total_conns{native_region=\"$native_region\", native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "redis_idle_conns",
     "type": "timeseries",
     "description": "当前空闲连接数",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 77 },
     "targets": [
      {
       "expr": "avg by(name)(redis_idle_conns{native_region=\"$native_region\", native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "redis_timeouts",
     "type": "timeseries",
     "description": "每秒等待连接超时的次数",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "avg by(name)(rate(redis_timeouts{native_region=\"$native_region\", native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[1m]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "redis_stale_conns",
     "type": "timeseries",
     "description": "每秒被移除的过期连接数",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "avg by(name) (rate(redis_stale_conns{native_region=\"$native_region\", native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[1m]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "redis_command_latency",
     "type": "timeseries",
     "description": "命令执行时延(μs)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by(name)(rate(redis_command_latency_sum{native_region=\"$native_region\", native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[1m])) / avg by(name) (rate(redis_command_latency_count{native_region=\"$native_region\", native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[1m]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "redis_check_latency",
     "type": "timeseries",
     "description": "ping 服务器延时",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by(name)(rate(redis_check_latency_sum{native_region=\"$native_region\", native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[1m])) / avg by(name)(rate(redis_check_latency_count{native_region=\"$native_region\", native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[1m]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "redis_command",
     "type": "timeseries",
     "description": "每秒命令请求次数",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "avg by(name)(rate(redis_command{native_region=\"$native_region\", native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[1m]))",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod 视角",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "redis_hits",
     "type": "timeseries",
     "description": "每秒从池中成功获取空闲连接的次数",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(redis_hits{native_region=\"$native_region\", native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[1m])",
       "legendFormat": "{{pod_name}}-{{name}}"
      }
     ]
    },
    {
     "title": "redis_misses",
     "type": "timeseries",
     "description": "每秒未能从池中获取连接，需要新建连接的次数",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(redis_misses{native_region=\"$native_region\", native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[1m])",
       "legendFormat": "{{pod_name}}-{{name}}"
      }
     ]
    },
    {
     "title": "redis_total_conns",
     "type": "timeseries",
     "description": "池中总连接数（活跃 + 空闲）",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "redis_total_conns{native_region=\"$native_region\", native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}",
       "legendFormat": "{{pod_name}}-{{name}}"
      }
     ]
    },
    {
     "title": "redis_idle_conns",
     "type": "timeseries",
     "description": "当前空闲连接数",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "redis_idle_conns{native_region=\"$native_region\", native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}",
       "legendFormat": "{{pod_name}}-{{name}}"
      }
     ]
    },
    {
     "title": "redis_stale_conns",
     "type": "timeseries",
     "description": "每秒被移除的过期连接数",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(redis_stale_conns{native_region=\"$native_region\", native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[1m])",
       "legendFormat": "{{pod_name}}-{{name}}"
      }
     ]
    },
    {
     "title": "redis_timeouts",
     "type": "timeseries",
     "description": "每秒等待连接超时的次数",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(redis_timeouts{native_region=\"$native_region\", native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[1m])",
       "legendFormat": "{{pod_name}}-{{name}}"
      }
     ]
    },
    {
     "title": "redis_command_latency",
     "type": "timeseries",
     "description": "命令执行时延(μs)",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "irate(redis_command_latency_sum{native_region=\"$native_region\", native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[1m]) / rate(redis_command_latency_count{native_region=\"$native_region\", native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[1m])",
       "legendFormat": "{{pod_name}}-{{name}}-{{command}}"
      }
     ]
    },
    {
     "title": "redis_check_latency",
     "type": "timeseries",
     "description": "ping 服务器延时",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "irate(redis_check_latency_sum{native_region=\"$native_region\", native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[1m]) / irate(redis_check_latency_count{native_region=\"$native_region\", native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[1m])",
       "legendFormat": "{{pod_name}}-{{name}}"
      }
     ]
    },
    {
     "title": "redis_command",
     "type": "timeseries",
     "description": "每秒命令请求次数",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(redis_command{native_region=\"$native_region\", native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[1m])",
       "legendFormat": "{{pod_name}}-{{name}}-{{command}}"
      }
     ]
    }
   ]
  }
 ]
}