{
 "title": "服务运行监控",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "native_env",
    "label": "环境",
    "query": {
     "query": "label_values(runtime_cpu_load_1,native_env)"
    }
   },
   {
    "name": "app",
    "label": "指标名",
    "query": {
     "query": "label_values(runtime_cpu_load_1{native_env=\"$native_env\"},app)"
    }
   },
   {
    "name": "pod_name",
    "label": "实例名",
    "query": {
     "query": "label_values(runtime_cpu_load_1{app=\"$app\"},pod_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "runtime_cpu_load_1",
   "type": "timeseries",
   "description": "1min 内的 CPU 的 running 队列上平均 task 数量",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "runtime_cpu_load_1{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "runtime_cpu_load_5",
   "type": "timeseries",
   "description": "5min 内的 CPU 的 running 队列上平均 task 数量",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "runtime_cpu_load_5{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "runtime_cpu_load_15",
   "type": "timeseries",
   "description": "15min 内的 CPU 的 running 队列上平均 task 数量",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "runtime_cpu_load_15{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "runtime_cpu_total",
   "type": "timeseries",
   "description": "机器逻辑核心数(硬件)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "runtime_cpu_total{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "runtime_cpu_usage_percent",
   "type": "timeseries",
   "description": "CPU 使用率",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "runtime_cpu_usage_percent{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "runtime_gc_num",
   "type": "timeseries",
   "description": "最近 5min 每秒钟 GC 发生次数",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(runtime_gc_num{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[5m])",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "每次 GC 暂停时间(μs)",
   "type": "timeseries",
   "description": "每次 GC 暂停时间(μs)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(runtime_gc_pause_total{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[5m]) / rate(runtime_gc_num{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[5m]) / 1000",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "runtime_goroutine_num",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "runtime_goroutine_num{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "runtime_mem_alloc",
   "type": "timeseries",
   "description": "当前活跃分配的堆内存字节数",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "runtime_mem_alloc{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "runtime_mem_heap_alloc",
   "type": "timeseries",
   "description": "实时堆内存使用量",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "runtime_mem_heap_alloc{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "runtime_mem_heap_object_num",
   "type": "timeseries",
   "description": "当前堆上存活的对象数量",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "K" } },
   "targets": [
    {
     "expr": "runtime_mem_heap_object_num{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}/1000",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "runtime_mem_system_alloc",
   "type": "timeseries",
   "description": "Go 运行时系统内存占用",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "runtime_mem_system_alloc{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "runtime_mem_total",
   "type": "timeseries",
   "description": "硬件内存数量",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "runtime_mem_total{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "runtime_mem_usage_percent",
   "type": "timeseries",
   "description": "内存使用率",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "runtime_mem_usage_percent{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  }
 ]
}