{
 "title": "OrderBook 监控",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "symbol",
    "label": "交易对",
    "query": {
     "query": "label_values(rd_infra_orderbook_monitor, symbol)"
    }
   },
   {
    "name": "exchange",
    "label": "期货/现货",
    "query": {
     "query": "label_values(rd_infra_orderbook_monitor{symbol=~\"$symbol\"},exchange)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CEXMonitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$symbol($exchange) - ask1 - price",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rd_infra_orderbook_monitor{line=\"bn_ask1_price\",symbol=~\"$symbol\",exchange=~\"$exchange\"}",
     "legendFormat": "Binance"
    },
    {
     "expr": " rd_infra_orderbook_monitor{line=\"cex_ask1_price\",symbol=~\"$symbol\",exchange=~\"$exchange\"}",
     "legendFormat": "CEXMonitor"
    }
   ]
  },
  {
   "title": "$symbol($exchange) - ask1 - PriceDiff(%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(rd_infra_orderbook_monitor{line=\"bn_ask1_price\",symbol=~\"$symbol\",exchange=~\"$exchange\"} - on() rd_infra_orderbook_monitor{line=\"cex_ask1_price\",symbol=~\"$symbol\",exchange=~\"$exchange\"}) / on() rd_infra_orderbook_monitor{line=\"cex_ask1_price\",symbol=~\"$symbol\",exchange=~\"$exchange\"} * 100",
     "legendFormat": "Ask1 - Price"
    }
   ]
  },
  {
   "title": "$symbol($exchange) - ask1 - quantity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rd_infra_orderbook_monitor{line=\"bn_ask1_qty\",symbol=~\"$symbol\",exchange=~\"$exchange\"}",
     "legendFormat": "Binance"
    },
    {
     "expr": "rd_infra_orderbook_monitor{line=\"cex_ask1_qty\",symbol=~\"$symbol\",exchange=~\"$exchange\"}",
     "legendFormat": "CEXMonitor"
    }
   ]
  },
  {
   "title": "$symbol($exchange) - ask1 - QuantityDiff",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rd_infra_orderbook_monitor{line=\"bn_ask1_qty\",symbol=~\"$symbol\",exchange=~\"$exchange\"} - on() rd_infra_orderbook_monitor{line=\"cex_ask1_qty\",symbol=~\"$symbol\",exchange=~\"$exchange\"}",
     "legendFormat": "Ask1 - Quantity"
    }
   ]
  },
  {
   "title": "$symbol($exchange) - bid1 - price",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rd_infra_orderbook_monitor{line=\"bn_bid1_price\",symbol=~\"$symbol\",exchange=~\"$exchange\"}",
     "legendFormat": "Binance"
    },
    {
     "expr": " rd_infra_orderbook_monitor{line=\"cex_bid1_price\",symbol=~\"$symbol\",exchange=~\"$exchange\"}",
     "legendFormat": "CEXMonitor"
    }
   ]
  },
  {
   "title": "$symbol($exchange) - bid1 - PriceDiff(%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(rd_infra_orderbook_monitor{line=\"bn_bid1_price\",symbol=~\"$symbol\",exchange=~\"$exchange\"} - on() rd_infra_orderbook_monitor{line=\"cex_bid1_price\",symbol=~\"$symbol\",exchange=~\"$exchange\"}) / on() rd_infra_orderbook_monitor{line=\"cex_bid1_price\",symbol=~\"$symbol\",exchange=~\"$exchange\"} * 100",
     "legendFormat": "Bid1 - price"
    }
   ]
  },
  {
   "title": "$symbol($exchange) - bid1 - quantity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "rd_infra_orderbook_monitor{line=\"bn_bid1_qty\",symbol=~\"$symbol\",exchange=~\"$exchange\"}",
     "legendFormat": "Binance"
    },
    {
     "expr": "rd_infra_orderbook_monitor{line=\"cex_bid1_qty\",symbol=~\"$symbol\",exchange=~\"$exchange\"}",
     "legendFormat": "CEXMonitor"
    }
   ]
  },
  {
   "title": "$symbol($exchange) - bid1 - QuantityDiff",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rd_infra_orderbook_monitor{line=\"bn_bid1_qty\",symbol=~\"$symbol\",exchange=~\"$exchange\"} - on() rd_infra_orderbook_monitor{line=\"cex_bid1_qty\",symbol=~\"$symbol\",exchange=~\"$exchange\"}",
     "legendFormat": "Bid-1 - Quantity"
    }
   ]
  }
 ]
}