{
 "title": "服务运行监控",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "native_env",
    "label": "环境",
    "query": {
     "query": "label_values(runtime_cpu_load_1,native_env)"
    }
   },
   {
    "name": "app",
    "label": "应用名",
    "query": {
     "query": "label_values(runtime_cpu_load_1{native_env=\"$native_env\"},app)"
    }
   },
   {
    "name": "pod_name",
    "label": "实例名",
    "query": {
     "query": "label_values(runtime_cpu_load_1{app=\"$app\", native_env=\"$native_env\"},pod_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "MySQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "mysql_max_open_connections",
     "type": "timeseries",
     "description": "数据库最大开放连接数",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "mysql_max_open_connections{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}",
       "legendFormat": "{{pod_name}} - {{name}}"
      }
     ]
    },
    {
     "title": "mysql_open_connections",
     "type": "timeseries",
     "description": "当前建立的连接总数（使用中 + 空闲）",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "mysql_open_connections{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}",
       "legendFormat": "{{pod_name}} - {{name}}"
      }
     ]
    },
    {
     "title": "mysql_idle",
     "type": "timeseries",
     "description": "当前空闲连接数",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
     "targets": [
      {
       "expr": "mysql_idle{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}",
       "legendFormat": "{{pod_name}} - {{name}}"
      }
     ]
    },
    {
     "title": "mysql_in_use",
     "type": "timeseries",
     "description": "当前正在使用的连接数",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
     "targets": [
      {
       "expr": "mysql_in_use{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}",
       "legendFormat": "{{pod_name}} - {{name}}"
      }
     ]
    },
    {
     "title": "mysql_wait_count(最好和 mysql_wait_duration 配合用)",
     "type": "timeseries",
     "description": "每秒等待连接的总次数",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 64 },
     "targets": [
      {
       "expr": " rate(mysql_wait_count{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[5m])",
       "legendFormat": "{{pod_name}} - {{name}}"
      }
     ]
    },
    {
     "title": "mysql_wait_duration(错误)",
     "type": "timeseries",
     "description": "等待连接的总时间",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 64 },
     "targets": [
      {
       "expr": "rate(mysql_wait_duration_sum{native_env=~\"$native_env\", app=~\"$app\"}[5m]) / rate(mysql_wait_duration_count{native_env=~\"$native_env\", app=~\"$app\"}[5m])",
       "legendFormat": "{{pod_name}} - {{name}}"
      }
     ]
    },
    {
     "title": "mysql_max_idle_closed",
     "type": "timeseries",
     "description": "因空闲连接数超限而关闭的连接",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 71 },
     "targets": [
      {
       "expr": "mysql_max_idle_closed{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}",
       "legendFormat": "{{pod_name}} - {{name}}"
      }
     ]
    },
    {
     "title": "mysql_max_idle_time_closed",
     "type": "timeseries",
     "description": "因空闲时间超限而关闭的连接",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 71 },
     "targets": [
      {
       "expr": "mysql_max_idle_time_closed{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}",
       "legendFormat": "{{pod_name}} - {{name}}"
      }
     ]
    },
    {
     "title": "mysql_max_lifetime_closed",
     "type": "timeseries",
     "description": "因生命周期超限而关闭的连接",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 78 },
     "targets": [
      {
       "expr": "mysql_max_lifetime_closed{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}",
       "legendFormat": "{{pod_name}} - {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Redis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "redis_hits",
     "type": "timeseries",
     "description": "每秒从池中成功获取空闲连接的次数",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 268 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(redis_hits{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[5m])",
       "legendFormat": "{{pod_name}}-{{name}}"
      }
     ]
    },
    {
     "title": "redis_misses",
     "type": "timeseries",
     "description": "每秒未能从池中获取连接，需要新建连接的次数",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 268 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(redis_misses{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[5m])",
       "legendFormat": "{{pod_name}}-{{name}}"
      }
     ]
    },
    {
     "title": "redis_total_conns",
     "type": "timeseries",
     "description": "池中总连接数（活跃 + 空闲）",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 275 },
     "targets": [
      {
       "expr": "redis_total_conns{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}",
       "legendFormat": "{{pod_name}}-{{name}}"
      }
     ]
    },
    {
     "title": "redis_idle_conns",
     "type": "timeseries",
     "description": "当前空闲连接数",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 275 },
     "targets": [
      {
       "expr": "redis_idle_conns{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}",
       "legendFormat": "{{pod_name}}-{{name}}"
      }
     ]
    },
    {
     "title": "redis_timeouts",
     "type": "timeseries",
     "description": "每秒等待连接超时的次数",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 282 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(redis_timeouts{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[5m])",
       "legendFormat": "{{pod_name}}-{{name}}"
      }
     ]
    },
    {
     "title": "redis_stale_conns",
     "type": "timeseries",
     "description": "每秒被移除的过期连接数",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 282 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(redis_stale_conns{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[5m])",
       "legendFormat": "{{pod_name}}-{{name}}"
      }
     ]
    },
    {
     "title": "redis_command_latency",
     "type": "timeseries",
     "description": "命令执行时延(μs)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 289 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rate(redis_command_latency_sum{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[5m]) / rate(redis_command_latency_count{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[5m])",
       "legendFormat": "{{pod_name}}-{{name}}-{{command}}"
      }
     ]
    },
    {
     "title": "redis_check_latency",
     "type": "timeseries",
     "description": "ping 服务器延时",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 289 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rate(redis_check_latency_sum{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[5m]) / rate(redis_check_latency_count{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[5m])",
       "legendFormat": "{{pod_name}}-{{name}}"
      }
     ]
    },
    {
     "title": "redis_command",
     "type": "timeseries",
     "description": "每秒命令请求次数",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 296 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(redis_command{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[5m])",
       "legendFormat": "{{pod_name}}-{{name}}-{{command}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "runtime_cpu_load_1",
     "type": "timeseries",
     "description": "1min 内的 CPU 的 running 队列上平均 task 数量",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "runtime_cpu_load_1{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "runtime_cpu_load_5",
     "type": "timeseries",
     "description": "5min 内的 CPU 的 running 队列上平均 task 数量",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "runtime_cpu_load_5{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "runtime_cpu_load_15",
     "type": "timeseries",
     "description": "15min 内的 CPU 的 running 队列上平均 task 数量",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "runtime_cpu_load_15{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "runtime_cpu_total",
     "type": "timeseries",
     "description": "机器逻辑核心数(硬件)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "runtime_cpu_total{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "runtime_cpu_usage_percent",
     "type": "timeseries",
     "description": "CPU 使用率",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "runtime_cpu_usage_percent{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "runtime_gc_num",
     "type": "timeseries",
     "description": "最近 5min 每秒钟 GC 发生次数",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(runtime_gc_num{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[5m])",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "每次 GC 暂停时间(μs)",
     "type": "timeseries",
     "description": "每次 GC 暂停时间(μs)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rate(runtime_gc_pause_total{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[5m]) / rate(runtime_gc_num{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}[5m]) / 1000",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "runtime_goroutine_num",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "runtime_goroutine_num{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "runtime_mem_alloc",
     "type": "timeseries",
     "description": "当前活跃分配的堆内存字节数",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "runtime_mem_alloc{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "runtime_mem_heap_alloc",
     "type": "timeseries",
     "description": "实时堆内存使用量",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "runtime_mem_heap_alloc{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "runtime_mem_heap_object_num",
     "type": "timeseries",
     "description": "当前堆上存活的对象数量",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "K" } },
     "targets": [
      {
       "expr": "runtime_mem_heap_object_num{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}/1000",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "runtime_mem_system_alloc",
     "type": "timeseries",
     "description": "Go 运行时系统内存占用",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "runtime_mem_system_alloc{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "runtime_mem_total",
     "type": "timeseries",
     "description": "硬件内存数量",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "runtime_mem_total{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "runtime_mem_usage_percent",
     "type": "timeseries",
     "description": "内存使用率",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "runtime_mem_usage_percent{native_env=~\"$native_env\", app=~\"$app\", pod_name=~\"$pod_name\"}",
       "legendFormat": "{{pod_name}}"
      }
     ]
    }
   ]
  }
 ]
}